"""Add image_url to Facility

Revision ID: 1409b3878d93
Revises: b94fc463a046
Create Date: 2025-08-11 23:02:05.871910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1409b3878d93'
down_revision = 'b94fc463a046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
